app:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix: /

base_api_v1:
    path: /api/v1/

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

nelmio_api_swagger:
    resource: "@NelmioApiDocBundle/Resources/config/swagger_routing.yml"
    prefix: /api/doc.json